platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings! ##消除警告
target 'YeeNewsChannel' do
    
  pod 'AFNetworking', '~> 3.1.0'
  pod 'MJRefresh', '~> 3.1.12'
  pod 'Masonry', '~> 1.0.1'
  pod 'SwipeTableView', '~> 0.2.6'  #半塘首页悬停效果
  pod 'SDWebImage', '~> 3.7.5'
  pod 'MJExtension', '~> 3.0.13'
  
end
